### ISSUE TITLE
Error while preprocessing the data

### ISSUE THREAD

**Issue by kailasmachineai** [aishj10/swap-net-summer#2]
Traceback (most recent call last):
  File "preprocess.py", line 469, in <module>
    make_vocab(os.path.join(finished_files_dir,'training_list.txt'))
  File "preprocess.py", line 317, in make_vocab
    article=_DIGIT_RE.sub(" 0",article)
TypeError: cannot use a bytes pattern on a string-like object

**Comment by RyanOngAI** [comment]
Yo you managed to fix the above problem yet? I faced the same issue.
